### ISSUE TITLE
Scrambler RegEx wont catch anything with new line/carriage return

### ISSUE THREAD

**Issue by BrutalBirdie** [indilo53/fxserver-resource-scrambler#5]
This issue will result in many script not working correctly since many programmers choose to make a new line/carriage return after for example TriggerEvent/AddEventHandler yada yada yada

Goode code, this will be scrambled
```lua
Citizen.CreateThread(
    function()
        while ESX == nil do
            TriggerEvent("esx:getSharedObject", function(obj) ESX = obj end)
            Citizen.Wait(0)
        end
    end
)
```
This will result in 
```lua
Citizen.CreateThread(
    function()
        while ESX == nil do
            TriggerEvent("5c537969-ccaf-40c7-87ff-8437348ff90f", function(obj) ESX = obj end)
            Citizen.Wait(0)
        end
    end
)
```

Bad code this will **NOT** get scrambled
```lua
Citizen.CreateThread(
    function()
        while ESX == nil do
            TriggerEvent(
                "esx:getSharedObject",
                function(obj)
                    ESX = obj
                end
            )
            Citizen.Wait(0)
        end
    end
)
```
This will not get scrambled. The RegEx given 

A fix suggestion would be an updated RegEx. https://github.com/indilo53/fxserver-resource-scrambler/blob/fc84404f72d7c71f2f7d9735b474d93dd62ec512/resourcescrambler.js#L11

I would propose this RegEx
```regex
\((\n["'](.*?)["']|\n\s+["'](.*?)["']|.+["'](.*?)["']|["'](.*?)["'])/g
```
Can be tested here
https://regex101.com/r/OSZebN/1
This way the last group will always (as far as I tested) find the Event.

I would love some feedback =)
@indilo53

ps:
Worked with @NebelRebell on this issue.

**Comment by indilo53** [comment]
Let's make a PR and I merge this ! thanks

**Comment by BrutalBirdie** [comment]
I tried to build it myself but my node-gyp denied to install node-lua and this got me stuck for 30 minutes then I was frustrated and kicked chair :)

@indilo53 did you check the RegEx?
